# Generated by Django 5.1.3 on 2024-12-01 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='imagens/')),
                ('descricao', models.TextField(blank=True)),
                ('data_captura', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
